url: http://en.mytory.net
title: Talking through Web
description: "WordPress, CSS, JS, jQuery, etc..."

timezone: "Asia/Seoul"
paginate: 10
paginate_path: "page/:num"

email: "mail@mytory.net"
twitter_username: "mytory"
github_username: "mytory"